### ISSUE TITLE
distribute XP

### ISSUE THREAD

**Issue by Shenanigan83** [ironmonk88/monks-tokenbar#81] opened 2021-04-10 16:23 UTC
When you open the window to distribute XP. At first if you enter a number with the "do not divide XP". It doesnt update the XP of the players.

You need to switch to another type of distributing XP and then reselect "do not divide XP" option. Then it will work as intended and the number of XP you put in will update on players respectively

**Comment by ironmonk88** [comment] 2021-04-18 17:11
What system are you using?  I'm having a hard time reproducing this.

**Comment by Shenanigan83** [comment] 2021-04-19 02:54
Its pathfinder 2e. I tested it again and it seems to work now. Perhaps I overlooked something. My bad.  you can close this bug thanks :)

**Comment by ironmonk88** [comment] 2021-04-20 00:10
Maybe something got shifted in the code and fixed it... hence why I couldn't reproduce it.
No worries, if it shows up again let me know.  :-)
Closing the ticket for now.

**Closed by ironmonk88** 2021-04-20 00:10 UTC
