### ISSUE TITLE
Requested rolls fail in attribute rolls in Savage Worlds

### ISSUE THREAD

**Issue by montver** [ironmonk88/monks-tokenbar#308] opened 2022-11-20 08:43 UTC
since the last update of the savage worlds system, attribute rolls fail in requested rolls. I believe that the author of the system made a change in the way attributes are launched or changed and must have caused this bug.

System version: Savage worlds Adventure Edition 2.1.4
Version Foundry v10.290

![imagen_2022-11-20_094308491](https://user-images.githubusercontent.com/72754407/202893217-2da7909e-c0db-47af-a20c-007142d9dbf8.png)

![imagen_2022-11-20_093500762](https://user-images.githubusercontent.com/72754407/202892955-1924dc37-d058-43c5-bd4a-bb2da4230f15.png)

**Comment by jseeley150** [comment] 2023-06-08 19:15
Changing swade-rolls.js line 104 from

`let item = actor.items.find(i => i.name == request.key && i.type == 'skill');`

to

`let item = actor.items.find(i => MonksTokenBar.slugify(i.name) == request.key && i.type == 'skill');`

resolves the issue. This is an issue caused by case sensitivity.

**Comment by ironmonk88** [comment] 2023-12-17 20:50
Attribute should be fixed in the latest version.

**Closed by ironmonk88** 2023-12-17 20:50 UTC
Labels: fixed waiting for release
