### ISSUE TITLE
[BUG] Tool Not Displayed for GMs for DnD5e 4.0.4 / Foundry 12.331

### ISSUE THREAD

**Issue by Red5MT** [ironmonk88/monks-tokenbar#527] opened 2024-10-12 04:05 UTC
Someone on Reddit came across this. When I looked at it to help them, I was able to confirm that there is a bug. I could find no mention of this error or an incomatibility (or compatibility) with DnD 4.0 on Github, so I thought best to report it.

When a world is created with only the Tokenbar module enabled, the tool will be be displayed for GMs when the world loads. However, the tool is active in the background as an ALT-R will bring up the Roll Request dialogue. The tool is available for players if the option is enabled.

I tried enabling/disabling a number of settings related to Experience (due to the console error below) and enabling/disabling the Tokenbar, but they had no effect.

CONSOLE ERROR:

_**foundry.js:635 Foundry VTT | Error thrown in hooked function 'ready' for hook 'ready'
#call @ foundry.js:635Understand this warning
foundry.js:655 Error: Error thrown in hooked function 'ready' for hook 'ready'. "dnd5e.disableExperienceTracking" is not a registered game setting
    at Hooks.onError (foundry.js:654:24)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at Game.setupGame (foundry.js:9098:11)
    at async Game._initializeGameView (foundry.js:10432:5)
    at async Game.initialize (foundry.js:8995:5)Caused by: Error: "dnd5e.disableExperienceTracking" is not a registered game setting
    at #assertKey (foundry.js:3402:42)
    at ClientSettings.get (foundry.js:3334:26)
    at get showXP (dnd5e-rolls.js:69:31)
    at DnD5eRolls.getButtons (base-rolls.js:152:70)
    at new TokenBar (tokenbar.js:97:45)
    at Object.ready [as fn] (monks-tokenbar.js:434:38)
    at #call (foundry.js:632:20)
    at Hooks.callAll (foundry.js:589:17)
    at Game.setupGame (foundry.js:9098:11)
    at async Game._initializeGameView (foundry.js:10432:5)**_

Foundry 12.331 / DnD5e 4.0.4 / Tokenbar 12.02

**Comment by Red5MT** [comment] 2024-10-12 15:32
Looks like this is a duplicate of  [Ticket 522](https://github.com/ironmonk88/monks-tokenbar/issues/522#issuecomment-2403983486). Closing this ticket.

**Comment by Red5MT** [comment] 2024-10-12 15:33
Looks like this is a duplicate of  [Ticket 522](https://github.com/ironmonk88/monks-tokenbar/issues/522#issuecomment-2403983486). Closing this ticket.

**Comment by ironmonk88** [comment] 2024-10-23 20:53
closing duplicate of #522

**Closed by ironmonk88** 2024-10-23 20:53 UTC
Labels: duplicate
