### ISSUE TITLE
Option to colourize TokenBar icons

### ISSUE THREAD

**Issue by weepingminotaur** [ironmonk88/monks-tokenbar#423] opened 2023-10-31 18:06 UTC
To help each stat stand out, it would be excellent if we had the option to colourize whatever icons are in use on the TokenBar, similar to the option provided in the Pathfinder Interactive Token Tooltip module. I'd be fine with either a set colour scheme defined by MTB or the option to set a colour for each icon.

**Comment by ironmonk88** [comment] 2023-12-02 20:16
Duplicate of #417

**Closed by ironmonk88** 2023-12-02 20:16 UTC
Labels: duplicate, enhancement
