### ISSUE TITLE
[Bug] Request a roll feature disappeared from the Token Bar when updating the PF2 system to 6.1.0

### ISSUE THREAD

**Issue by demotech89** [ironmonk88/monks-tokenbar#502] opened 2024-07-21 16:02 UTC
Request a roll feature disappeared from the Token Bar when updating the PF2 system to 6.1.0

It continues to work after rolling back to 6.0.4 PF2 system update.

**Comment by ironmonk88** [comment] 2024-07-21 23:52
Duplicate of #503

**Closed by ironmonk88** 2024-07-21 23:52 UTC
Labels: duplicate
