### ISSUE TITLE
[BUG] Unable to open Toolbar menu to left of icons

### ISSUE THREAD

**Issue by thystra** [ironmonk88/monks-tokenbar#523] opened 2024-09-22 03:52 UTC
**Describe the bug**
Tool bar will not expand small icons to the left of character portraits. 

**To Reproduce**
1. Load game
2. 
**Expected behavior**
Able to expand toolbar and use buttons to control movement etc. 

**Screenshots**
![image](https://github.com/user-attachments/assets/1caff5d8-78c2-482a-8332-540ca10ebed2)
![image](https://github.com/user-attachments/assets/f65cc6e2-dfef-4543-a695-99382c4c2f5a)

**Please complete as much of the following information as possible:**
 - Browser vivaldi 6.9.3447.46 (Stable channel) stable (64-bit)
 - Foundry Version [12 331]
 - System [DND5e 4.0.2]
 - Module version 12.02
 - Are there any errors in the console [e.g. press F12 and look for red text] Yes
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. Yes,. Bar doesn't load when it is the only module. 
![image](https://github.com/user-attachments/assets/c3106843-98f9-46d9-8b7c-b2341206db48)
![image](https://github.com/user-attachments/assets/14937428-109d-4d50-b636-bafaab20c8fd)

**Additional context**

**Comment by Evilkeeper** [comment] 2024-09-22 17:25
this is a duplicate of #522

**Comment by Nedrapter** [comment] 2024-09-27 13:24
Having the same issue. Makes Tokenbar unusable pretty much.

**Comment by EvldoaTV** [comment] 2024-10-26 18:33
Any ETA on a  fix for this issue Token bar has been unusable since 4.0 update I miss it

**Comment by thystra** [comment] 2024-10-27 03:26
Until it's fixed, make the manual edit to the files on your server and it will work.

**Comment by EvldoaTV** [comment] 2024-10-27 06:02
not everyone knows how to do such things :P

**Comment by ironmonk88** [comment] 2024-10-27 17:42
Closing since this looks like a duplicate of #522

**Closed by ironmonk88** 2024-10-27 17:42 UTC
Labels: duplicate
