### ISSUE TITLE
[BUG] Errors in console since last update

### ISSUE THREAD

**Issue by CaosFR** [ironmonk88/monks-tokenbar#534] opened 2024-10-29 18:39 UTC
**Describe the bug**
A have few error in the console since last update of your module

The first error is the same of this "https://github.com/ironmonk88/monks-tokenbar/issues/533" but not the others

**To Reproduce**
Just update your module and lunch a world

**Expected behavior**
I will reply the concrete consequences of its bugs (not yet verified). This is to inform you of the errors caused by the update.

**Screenshots**
![image](https://github.com/user-attachments/assets/5b765441-e06a-498c-97b7-9d7c0a04a693)
![image](https://github.com/user-attachments/assets/a4a563f7-59f5-4cd3-9f68-3942269a9ddf)

**Please complete as much of the following information as possible:**
 - Browser Chromium 129
 - Foundry Version : latest
 - System DnD5e 3.3.1
 - Module version : latest

**Comment by CaosFR** [comment] 2024-10-29 22:49
Update : The bar is unusable, there are no buttons, and its behavior is erratic (e.g., it won't exit combat mode).

**Comment by ironmonk88** [comment] 2024-10-29 22:56
Duplicate of #533 
You need to update D&D

**Closed by ironmonk88** 2024-10-29 22:56 UTC
Labels: duplicate

**Comment by CaosFR** [comment] 2024-10-29 22:59
As I said, I won't be updating Foundry for the time being. Many like me will wait until the modules are compatible.

Please mention in your module manifest that this is only for v4, this will be a blessing for many.

**Comment by Crowguard** [comment] 2024-10-29 23:46
@CaosFR It was not intended to be a 4.x only update, but just ended up turning into one due to whatever changes were made to make it compatible with D&D's 4.x happening to break Tokenbar in previous D&D versions. Unfortunately, Foundry not allowing multiple versions of a system to be installed makes it hard to test backwards compatibly with modules.

Blame this on D&D 5e introducing breaking changes without caring about modules or providing any shim methods.

**Comment by CaosFR** [comment] 2024-11-01 08:05
Dang, that's really impactful for you. I understand better, good luck with the devellopement.
